application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # 7 day


spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: bookstore

springdoc:
  swagger-ui:

    path: /swagger-ui.html
    enabled: true

